steps:
  # Step 1: Build using the Git Short SHA as the tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/demonotes-app:$SHORT_SHA', '.']

  # Step 2: Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/demonotes-app:$SHORT_SHA']

  # Step 3: Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'demonotes-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/demonotes-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# This enables the "Images" tab in Cloud Build history
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/demonotes-app:$SHORT_SHA'
